### ISSUE TITLE
Replace Url param when use prototype

### ISSUE THREAD

**Issue by ghost** [Fl0pZz/Apipie#25]
**Have:**
```js
    {
        name: 'user',
        method: 'get',
        url: '/api/v1/users',
    },
````
**Need to use:**
```js
api.user({'url': url});
```
**What expected?**
Replace url in object-case and make request

**What actually happened?**
url not replaced.

**Comment by dimensi** [comment]
Feature: Make it possible to pass url on the call.
Parse the url and check the path to match and substitute the received values from the received url.
