### ISSUE TITLE
В axios не доходит FormData

### ISSUE THREAD

**Issue by heisenberg-kz** [Fl0pZz/Apipie#31]
Столкнулся с проблемой FormData
Версии

`"apipie": "^0.14.0", (с 0.15 такая же проблема)
"axios": "^0.16.2",`

В axios не доходит new FormData(), продебажил data
` transformRequest: [function (data, headers) {  console.log(data) }` возвращает пустой объект

`{
            name: 'updateBackground', method: 'post', url: 'background', DATA, options: {
                transformRequest: [function (data, headers) {
                    console.log(data);
                }]
            }
}`

`
let formData = new FormData();
fromData.append('test', 'test');
api.users.updateBackground({data: formData}).then()
`

p.s. если отправлять с axios.post тужу самую FormData, то все в порядке

**Comment by Piterden** [comment]
```js
let formData = new FormData(); fromData.append('test', 'test'); 
```

`formData` и `fromData`

**Comment by heisenberg-kz** [comment]
Я тут сделал опечатку, в коде нет опечатки

**Comment by Piterden** [comment]
Дай ссылку на код - погонять...

![image](https://user-images.githubusercontent.com/5930429/45253780-ba1fec80-b375-11e8-9364-078edbd3aa65.png)

**Comment by heisenberg-kz** [comment]
https://jsfiddle.net/doroshenkomisha/eywraw8t/346236/
Cоответственно если запрос уйдет у него не будет Content-type: multipart/form-data

**Comment by heisenberg-kz** [comment]
Я уже пробовал передавать просто объект и в transformRequest преобразовывать его в FormData, тогда все хорошо отправляется. Но apipie "режит" файлы в параметрах объектах.

**Comment by Piterden** [comment]
https://jsfiddle.net/Piterden/eywraw8t/346273/

**Comment by heisenberg-kz** [comment]
Не совсем понял, что Вы этим хотели сказать, если то что нужно устанавливать заголовок Content-type, то это ничего не меняет.
Если делать например так, то заголовки в порядке
https://jsfiddle.net/doroshenkomisha/eywraw8t/348052/
![image](https://user-images.githubusercontent.com/9706439/45260873-78924e80-b414-11e8-8ebd-0b63d5b48641.png)

**Comment by Piterden** [comment]
Я хотел сказать, что объект headers не похож на заголовки

**Comment by heisenberg-kz** [comment]
т.е. что с apipie все хорошо и это я что-то не так делаю? 
У Вас случайно, нет примера с работающей formData? 
Мне кажется, там какие-то траблы с мержем options, перед тем как передается в axios

**Comment by Piterden** [comment]
Дело в том, что FormData не имеет options.

**Comment by heisenberg-kz** [comment]
Я нашел проблему тут, точнее с опцией {clone: true}
https://github.com/Fl0pZz/Apipie/blob/old_v0.14/lib/create-rest-tree.js#L106

после мержа data: FormData становится data: {}

**Comment by Piterden** [comment]
Это потому что FormData и есть {}

Наберите в консоли браузера `fd = new FormData(); fd.append('test', 'test'); fd`

**Comment by Piterden** [comment]
```js
fd = new FormData();
fd.append('test', 'test');
Array.from(fd.keys()).reduce((acc, cur) => {
  acc[cur] = fd.get(cur)
  return acc
}, {})
```
![image](https://user-images.githubusercontent.com/5930429/45291968-5aa01900-b4fc-11e8-9f86-c2ae8e9235fb.png)

**Comment by heisenberg-kz** [comment]
![image](https://user-images.githubusercontent.com/9706439/45292023-b3c87680-b515-11e8-91c1-fa34d6587bd3.png)
ну так объект FormData {}, а не просто объект {}

ладно, жаль что мы друг друга не понимаем

**Comment by Piterden** [comment]
```js
const fd = new FormData();
fd.append('test', 'test');
console.log(JSON.parse(JSON.stringify({ fd })))
```
Объект `FormData` не имеет свойств в любом случае. Он содержит методы и итераторы. Для получения объекта с ключами-значениями используйте мой метод с `.reduce`.

**Comment by heisenberg-kz** [comment]
FormData не работает как обычный json объект. 
```js
const fd = new FormData();
fd.append('foo', 'bar');
console.log(fd.get('foo')); //bar

const jsonObject = JSON.parse(JSON.stringify({ fd }));
console.log(jsonObject.fd.get('foo')); // TypeError: jsonObject.fd.get is not a function
```

**Comment by Piterden** [comment]
Ну вы Кэп!!!
А я что вам пытаюсь сказать второй день?!
Перечитайте мой предыдущий пост...

**Comment by heisenberg-kz** [comment]
Так я пытаюсь вам показать, что в axios нужен именно formData, чтоб файлы отправлять на сервер. А не объект с костылями

**Comment by Piterden** [comment]
Ну и подавайте туда FormData. Какой пруф вы имеете от использования Apipie?

**Comment by heisenberg-kz** [comment]
так я и передаю туда FormData, а отправляет его не как formData, а как пустой объект

**Comment by Piterden** [comment]
Куда туда?

**Comment by heisenberg-kz** [comment]
в apipie. Проблем с axios нет

**Comment by Piterden** [comment]
А зачем вам apipie? Никогда не пользовался ни чем подобным. Какой в нем смысл?

**Comment by heisenberg-kz** [comment]
Вот это я орнул сейчас. Я думал, что Вы имеете отношение к apipie.

**Comment by Piterden** [comment]
Тогда было бы написано contributor. Я просто стою на вотче и всё это легаси, если честно.. ))

![image](https://user-images.githubusercontent.com/5930429/45294117-03ea0d80-b503-11e8-913e-3190d831b5fd.png)

**Comment by heisenberg-kz** [comment]
Нет, я видел что Вы не котрибьютер, просто так уверенно отвечали, и подумал, что хорошо знакомы с apipie.

**Comment by heisenberg-kz** [comment]
Смысл пользоваться, как раз в этом 
https://github.com/Fl0pZz/Apipie/blob/old_v0.14/docs/ru_Ru/whywhywhy.md

**Comment by Piterden** [comment]
А покажите пожалуйста ваш конфиг для apipie, если есть такая возможность. Вероятно там нужно добавить исключение...

**Comment by heisenberg-kz** [comment]
Я уже решил проблему форком
